### ISSUE TITLE
Home page site name gets cut off on large/wide monitors

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-aldine#105]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Aldine](http://github.com/pressbooks/pressbooks-aldine/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using Aldine as your network's root theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-aldine) to see if your bug or enhancement is already listed?

### Description

On large monitors, the home page site name gets higher the wider the screen, until it cuts off the text.

### Steps to Reproduce

1. Open a pressbooks site running Aldine to the main landing page.
2. On a large or high resolution monitor, pull the page wider and notice how the text moves up the wider the screen.
3. See that at certain wide widths, the site name is cut off.

Screenshot 1 (width 1108)
![screen shot 2018-03-06 at 8 31 16 am](https://user-images.githubusercontent.com/29982981/37034967-ffd3b5ee-2118-11e8-8a0a-8ff4129c1734.png)

Screenshot 2 (width 1276)
![screen shot 2018-03-06 at 8 31 33 am](https://user-images.githubusercontent.com/29982981/37035001-1c3018ae-2119-11e8-86d7-ff5a305ae0db.png)

Screenshot 3 (width 1520)
![screen shot 2018-03-06 at 8 31 49 am](https://user-images.githubusercontent.com/29982981/37035038-33ed6d02-2119-11e8-8b4f-e4991b8bc20b.png)

**Expected behavior:** 

I'd expect the site name to be visible and readable at all screen sizes.

**Actual behavior:** 

Information is cut off on the largest/highest resolution desktop monitors

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://oer.ed-beck.com/

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 64.0.3282.186
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

#### WordPress Configuration

Network URL: http://oer.ed-beck.com/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.0.0
Root Theme: Aldine
Root Theme Version: 1.0.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Candela LTI: 0.1
Candela Thin Exports: 0.1
Hypothesis: 0.5.0
LTI: 0.1
mPDF for Pressbooks: 3.1.0
Pressbooks: 5.0.0
Textbooks for Pressbooks: 4.0.0

#### Inactive Plugins

Akismet Anti-Spam: 4.0.3
CC Export for Pressbooks: 0.2.0
Hello Dolly: 1.6
Wp Show Site ID: 1.0.0

#### Server Configuration

PHP Version: 7.0.25-0ubuntu0.16.04.1
MySQL Version: 5.7.21
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 500M
Upload Max Size: 2000M
Post Max Size: 2000M
Upload Max Filesize: 2000M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Not Supported
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
I fixed this while addressing #102. Aldine 1.0.1 is coming out later today and should resolve the issue. Thanks for reporting!
