### ISSUE TITLE
If a book is archived, spammed or deleted, it should be removed from the catalog

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks-aldine#106]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Aldine](http://github.com/pressbooks/pressbooks-aldine/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using Aldine as your network's root theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-aldine) to see if your bug or enhancement is already listed?

### Description

maybe is about the same, but if a book is achive, we can still find the book in the catalog and also to open the book

achive or deactivate book. happen the same
![captura de pantalla 2018-03-07 a las 14 51 08](https://user-images.githubusercontent.com/3929177/37095851-533264f2-2217-11e8-9401-c653323b5255.png)

![captura de pantalla 2018-03-07 a las 14 59 39](https://user-images.githubusercontent.com/3929177/37096214-3a7dea2a-2218-11e8-8b1d-c78efa5073d4.png)

### Steps to Reproduce

achive or deactivate a book

**Expected behavior:** 
no longer we see the books in the catalog. no longer the users can read the book.

**Actual behavior:** 
we can see the books in the catalog. and we can open the book and to read it.

book in the catalog
![captura de pantalla 2018-03-07 a las 14 50 59](https://user-images.githubusercontent.com/3929177/37095853-55305372-2217-11e8-9d92-141a39a99b19.png)

archive book or deactivate book still available
![captura de pantalla 2018-03-07 a las 14 53 30](https://user-images.githubusercontent.com/3929177/37095872-5e687582-2217-11e8-85d1-8718f8517a08.png)

System Information

Pressbooks: [5.0.1]
WordPress: [4.9.4]
PHP: [7.0]
System Information
Root Blog Info

Root Blog ID: 1
Root Blog URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/
Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
WordPress Configuration

Network URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M
Pressbooks Configuration

Version: 5.0.1
Root Theme: Aldine
Root Theme Version: 1.0.0-RC.2
Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed
Must-Use Plugins

hm-autoloader.php: n/a
Network Active Plugins

Pressbooks: 5.0.1
Wordfence Security: 7.1.0
Root Blog Active Plugins
Inactive Plugins

mPDF for Pressbooks: 3.1.0
Textbooks for Pressbooks: 4.0.0
Server Configuration

PHP Version: 7.0.27
MySQL Version: 5.5.59
Webserver Info: Apache
PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 2M
Post Max Size: 8M
Upload Max Filesize: 2M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)
PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.35.0
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment]
If you are logged in as a network admin, you will still be able to read the book (that's the way WordPress multisite works). If I mark a book as "Archived", log out, and visit the book, I see this:

![screen shot 2018-03-07 at 10 15 20 am](https://user-images.githubusercontent.com/605361/37096882-76d9e942-21f0-11e8-9d85-0e5b8b654219.png)

Regarding your other point, we should remove books that have been archived from the catalog, so yes, that is a bug.

**Comment by colomet** [comment]
archived books yes. But 

> Deactivate reverses the activation step users go through when they signup for a site. It doesn’t permanently delete the site which can be reactivated at any time. Neither the front end nor the site admin screens are accessible

.

**Comment by colomet** [comment]
I see, Not admins but superadmins can.. ok. thanks
