### ISSUE TITLE
Front Page Catalog not displaying

### ISSUE THREAD

**Issue by fncll** [pressbooks/pressbooks-aldine#147]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

No catalog displays on the front page despite having the "Front Page Catalog" option checked in the customizer and two public books with "In Catalog" checked on the Network Admin > Books page. 

I have tested with multiple browsers and verified that there is no catalog content on the front page.

**Expected behavior:** See the catalog carousel on the front page.

**Actual behavior:** No catalog carousel, though user catalogs work fine.

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://openpress.alaska.edu/

#### Browser

Platform: OS X
Browser Name: Vivaldi
Browser Version: 2.1.1337.51
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.113 Safari/537.36 Vivaldi/2.1.1337.51

#### WordPress Configuration

Network URL: http://openpress.alaska.edu/
Network Type: Subdirectory
Version: 4.9.8
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.6.2
Root Theme: Aldine
Root Theme Version: 1.4.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

mPDF for Pressbooks: 3.2.3
Pressbooks: 5.6.2
Textbooks for Pressbooks: 4.2.2
Under Construction: 3.25

#### Root Blog Active Plugins

mPDF for Pressbooks: 3.2.3
Pressbooks: 5.6.2
Textbooks for Pressbooks: 4.2.2
Under Construction: 3.25

#### Inactive Plugins

Akismet Anti-Spam: 4.1
Hello Dolly: 1.7
Pressbooks LTI Provider: 1.0.0

#### Server Configuration

PHP Version: 7.2.12
MySQL Version: 5.7.24
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 150M
Post Max Size: 150M
Upload Max Filesize: 150M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.62.0
imagick: Not Installed
xsl: Installed

**Comment by fncll** [comment]
Here you go:

```
Array
(
    [pages] => 1
    [books] => Array
        (
            [0] => Array
                (
                    [title] => FNCLL TEST DEMO
                    [date-published] => 
                    [subject] => 
                    [link] => http://openpress.alaska.edu/fncll/
                    [metadata] => Array
                        (
                            [@context] => http://schema.org
                            [@type] => Book
                            [name] => FNCLL TEST DEMO
                            [inLanguage] => en
                            [image] => http://openpress.alaska.edu/wp-content/plugins/pressbooks/assets/dist/images/default-book-cover.jpg
                            [author] => Array
                                (
                                    [0] => Array
                                        (
                                            [@type] => Person
                                            [name] => chris
                                        )

                                )

                            [license] => Array
                                (
                                    [@type] => CreativeWork
                                    [url] => https://choosealicense.com/no-license/
                                    [name] => All Rights Reserved
                                )

                        )

                )

            [1] => Array
                (
                    [title] => Testing OpenPress
                    [date-published] => 2018-08-31
                    [subject] => ABA
                    [link] => http://openpress.alaska.edu/testing/
                    [metadata] => Array
                        (
                            [@context] => http://schema.org
                            [@type] => Book
                            [name] => Testing OpenPress
                            [alternativeHeadline] => an exploration of stuff
                            [inLanguage] => en
                            [disambiguatingDescription] => This book was written under a grey sky at the turn of evening before the frost. 
                            [image] => http://openpress.alaska.edu/wp-content/plugins/pressbooks/assets/dist/images/default-book-cover.jpg
                            [about] => Array
                                (
                                    [0] => Array
                                        (
                                            [@type] => Thing
                                            [identifier] => ABA
                                        )

                                    [1] => Array
                                        (
                                            [@type] => Thing
                                            [identifier] => AKH
                                        )

                                )

                            [author] => Array
                                (
                                    [0] => Array
                                        (
                                            [@type] => Person
                                            [name] => admin
                                        )

                                )

                            [publisher] => Array
                                (
                                    [@type] => Organization
                                    [name] => published in house 
                                    [address] => Array
                                        (
                                            [@type] => PostalAddress
                                            [addressLocality] => Fairbanks
                                        )

                                )

                            [datePublished] => 2018-08-31
                            [copyrightYear] => 2018
                            [copyrightHolder] => Array
                                (
                                    [@type] => Organization
                                    [name] => open copyright
                                )

                            [license] => Array
                                (
                                    [@type] => CreativeWork
                                    [url] => https://creativecommons.org/publicdomain/mark/1.0/
                                    [name] => Public Domain
                                )

                        )

                )

        )

)
```

**Comment by greatislander** [comment]
Huh. So, that is exactly the code that the front page uses to retrieve catalog data, and it seems to work as one would expect. I'm really stumped. Never seen this before.

**Comment by fncll** [comment]
It seems like some conditional isn't being met to include the catalog...see this snippet from the front page...none of the content is there?

```
</header> <!-- .header -->

<div id="content" class="site-content clearfix">
<div id="primary" class="content-area">
<main id="main" class="site-main">
</main><!-- #main -->
</div><!-- #primary -->
</div><!-- #content -->

<footer class="footer" role="contentinfo">
```

**Comment by greatislander** [comment]
Can you see if there's a page in your pages list called "Home", indicated as the Front Page?

<img width="244" alt="Screen shot of Home page in pages list" src="https://user-images.githubusercontent.com/605361/49550316-c8b46c00-f8b0-11e8-9ae7-ad26e72c0d87.png">

If there isn't a page marked as the "Front Page", that's probably the issue. Somehow the default content got deleted and the front page template isn't displaying; instead it's falling back to a list of posts (of which there are none). You can likely fix this by creating a new page called "Home" (you can call it whatever you want, just make the slug = `home`). Then, navigate to `/wp-admin/options-reading.php` and select the home page you created as follows:

<img width="451" alt="Screenshot of front page preferences" src="https://user-images.githubusercontent.com/605361/49550397-1a5cf680-f8b1-11e8-82ea-e9919a1cbbd5.png">

Let me know if this resolves the issue.

**Comment by fncll** [comment]
That was it! I should have thought of that. I suspect the other person who works on the server deleted that page. Thanks so much.

**Comment by greatislander** [comment]
Great! Thanks for taking the time to walk through it with me. I think it's probably a good idea to display some sort of admin notice if no page is selected to serve as the front page to make this kind of issue easier to spot in future.
