### ISSUE TITLE
Increase Font size button text doesn't change to Decrease Font size when activated

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-aldine#176]
### Description

In Pressbooks Book, when you press the "increase font size" button, the text changes to "decrease font size" to match expected behavior.

WIth the same feature now added to the catalog page, I would expect the same result, however the text remains "increase font size" whether it has been selected or not.

<img width="1399" alt="Screen Shot 2019-03-26 at 6 23 30 AM" src="https://user-images.githubusercontent.com/29982981/54990164-764aa880-4f90-11e9-90cc-eb0d52691ef3.png">
<img width="1401" alt="Screen Shot 2019-03-26 at 6 23 36 AM" src="https://user-images.githubusercontent.com/29982981/54990174-7a76c600-4f90-11e9-8f7f-1fca636e8e24.png">

### Steps to Reproduce

1. Upgrade to latest version of Aldine.
2. Select increase text size on the homepage
3. See that the text doesn't change

**Expected behavior:** 

I'd expect the behavior of the feature to be consistent between front pages and books.

**Actual behavior:** 

Text doesn't change on root site, but does on books.

**Comment by SteelWagstaff** [comment]
Thanks for sharing, Ed. We've added this to the backlog and will investigate soon.

**Comment by mcgratay** [comment]
Confirmed reproducible – affects every page on any network rootsite using the Aldine theme. 
Example: https://university.pressbooks.pub

**Comment by SteelWagstaff** [comment]
@beckej13820 we've discussed this feature as a team and think that rather than fixing this, it makes more sense at this point actually to remove it from Pressbooks entirely. There's no longer anything that this does that the user can't control/do themselves using the increase font size/decrease font size tools available to them in their own browser (https://www.computerhope.com/issues/ch000779.htm).

**Comment by cagp-dev-mtl** [comment]
I have opened two PR to revert this feature in Aldine and pressbooks-book:

Aldine:
https://github.com/pressbooks/pressbooks-aldine/pull/206

pressbooks-book:
https://github.com/pressbooks/pressbooks-book/pull/673

**Comment by SteelWagstaff** [comment]
@beckej13820 Just wanted to make sure you'd seen that we'd removed the 'increase font size' button entirely from recent releases of Pressbooks-book and Aldine.
