### ISSUE TITLE
Wordpress 5.2 login page error login_headertitle is depreciated

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-aldine#181]
### Description

On the login page of Aldine and books running McLuhan, There is an error message being shown above the login form.

![Screen Shot 2019-05-15 at 9 20 43 PM](https://user-images.githubusercontent.com/29982981/57853403-abff5700-77b3-11e9-9e2e-7ce7a597ec4d.png)

Error message reads:
Notice
: login_headertitle is
deprecated
since version 5.2.0! Use login_headertext instead. Usage of the title attribute on the login logo is not recommended for accessibility reasons. Use the link text instead. in
/var/www/html/wp-includes/functions.php
on line
4711

### Steps to Reproduce

1. Upgrade Pressbooks network to Wordpress 5.2
2. Go to the Login page with Debug turned on. 
3. See error message both on book login pages and network login pages.

**Expected behavior:** 

**Actual behavior:** 

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: https://oer.ed-beck.com/

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 74.0.3729.131
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

#### WordPress Configuration

Network URL: http://oer.ed-beck.com/
Network Type: Subdirectory
Version: 5.2
Language: en_US
WP_ENV: production
WP_DEBUG: Enabled
Memory Limit: 1000M

#### Pressbooks Configuration

Version: 5.8.0
Root Theme: Aldine
Root Theme Version: 1.6.2

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

GitHub Updater: 8.7.3
mPDF for Pressbooks: 3.3.1
Pressbooks: 5.8.0
Pressbooks LTI Provider: 1.3.0
Really Simple SSL: 3.1.5

#### Root Blog Active Plugins

GitHub Updater: 8.7.3
mPDF for Pressbooks: 3.3.1
Pressbooks: 5.8.0
Pressbooks LTI Provider: 1.3.0
Really Simple SSL: 3.1.5
WP QuickLaTeX: 3.8.6

#### Inactive Plugins

Akismet Anti-Spam: 4.1.2
CC Export for Pressbooks: 1.1.1
Equation Editor: 1.5
H5P: 1.13.1
Hello Dolly: 1.6
Hypothesis: 0.5.0
Openstax Import for Pressbooks: 1.2.4
Pressbooks Stats: 1.4.1
Textbooks for Pressbooks: 4.2.3
Wp Show Site ID: 1.0.2
WP Super Cache: 1.6.5

#### Server Configuration

PHP Version: 7.2.17-0ubuntu0.18.04.1
MySQL Version: 5.7.26
Webserver Info: Apache/2.4.29 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 1000M
Upload Max Size: 2000M
Post Max Size: 2500M
Upload Max Filesize: 2000M
Time Limit: 120
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.58.0
imagick: Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
@cagp-dev-mtl if you're able to take a look at this during this week, this might fit with some of the 5.3 prep testing you've been doing?

**Comment by connerbw** [comment]
Fixed in 5.9.1

https://github.com/pressbooks/pressbooks/commit/f23a765a0a069ec57de609dc8a9a44b300a082cb
