### ISSUE TITLE
Older networks may have broken CTA shortcodes

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-aldine#184]
Liz reports that old CTA shortcodes used a pattern that resembled the following `[aldine_call_to_action text="See plans and features" url="https://pressbooks.com/whatever"]`

The new shortcode params apparently replace `url` with `link`, so that the shortcode should read `[aldine_call_to_action text="See plans and features" link="https://pressbooks.com/whatever"]`

Liz believes that some older networks may still have CTA shortcodes which use the old pattern and thus have broken links. She writes "If you customized your network a long time ago, with the CTA code that existed at the time, the CTA links may have stopped working. (I noticed because this happened on the demo network--it's fixed there but I suppose it could be impacting client networks.)"

**Comment by greatislander** [comment]
This is entirely my fault! I’ll submit a PR.

**Comment by mcgratay** [comment]
Resolved.
