### ISSUE TITLE
Contact link customization not functioning on most networks 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-aldine#191]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Aldine](http://github.com/pressbooks/pressbooks-aldine/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using Aldine as your network's root theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-aldine) to see if your bug or enhancement is already listed?

### Description

We recently made a change that would allow admins to customize what the footer contact link on their network homepage directed to. 

![Screen Shot 2019-10-01 at 4 42 10 PM](https://user-images.githubusercontent.com/39064028/65998954-6b566080-e46a-11e9-86ac-7052e06209f1.png)

The functionality does not work as expected on most networks. Where broken, the contact link will only direct toward the Pressbooks.com Contact page, whether the form is active or not. The form can be active, but the link cannot be customized when the form is deactivated. When the form is disabled but the contact link field has not been customized, the contact link pointing toward the Pressbooks.com Contact page still displays in the network footer. 

The normal behavior is 
a) The contact form is enabled. The contact link directs toward the contact form. 
b) The contact form is disabled. The contact link is customized and points toward whatever link was entered by the network administrator. 
c) The contact form is disabled and no link is entered in the Contact Link field. The contact link disappears from the footer. 

It's possible that it only works on networks in which books are appointed a subdomain URL rather than a subdirectory URL. Tested networks and their results: 

https://textopress.com/ : Normal
https://university.pressbooks.pub : Not working
https://integrations.pressbooks.network : Not working

### Steps to Reproduce

1. Go to **Appearance > Customize** from the network rootsite dashboard
2. Select the **Contact Form** tab, then check the box to Show Contact Form
3. Publish changes and check the footer link to see if it redirects to the contact form
4. Return to the Contact Form customization tab, and deselect the contact form
5. Enter a custom link in the "Contact Link" cell
6. Publish changes and check footer link to see if it redirects to the custom link you provided
7. Return to the Contact Form customization tab, and remove the custom link 
8. Publish changes, then check the footer to see if the Contact link disappears

**Expected behavior:** Contact link is customizable on all networks

**Actual behavior:** Contact link is only customizable on some networks

**Comment by connerbw** [comment]
Our hosted networks have a configuration in `...bedrock/web/app/mu-plugins/telemetry.php`  

In those files is (usually) this code:

```php
add_filter( 'pb_contact_link', function () {
	return 'https://pressbooks.com/contact/';
} );
```

Other customers will have other values, sometimes an email, but most of the time I see pressbooks.com/contact. 

Contact link customization is completely ignored when we configure that value for a customer.

We can either

1) Rethink how that configuration should override the feature?
2) Turn off Contact link customization if manually configured?
3) @mcgratay Thoughts?

**Comment by connerbw** [comment]
Discussed in chat.

To recap, here's what happens for open source users:
a. no contact link
b. contact link goes to form [Aldine]
c. contact link goes to email (or link) [Aldine]

Here's what happens for customers now:
Link always goes to whatever is in PHP configuration. Checkbox makes form appear but the link at the bottom stays the same. 

The fix will:
a. contact link goes in whatever is in PHP configuration, or no contact link
b. contact link goes to form [Aldine]
c. contact link goes to email (or link) [Aldine]

**Comment by connerbw** [comment]
https://github.com/pressbooks/pressbooks/pull/1811
https://github.com/pressbooks/pressbooks-book/pull/609
https://github.com/pressbooks/pressbooks-aldine/pull/193

**Comment by connerbw** [comment]
Places to test:

![places-to-test-1](https://user-images.githubusercontent.com/812192/67326010-fa8fea80-f4e3-11e9-821d-36ec1dcb0340.png)

![places-to-test-2](https://user-images.githubusercontent.com/812192/67326007-fa8fea80-f4e3-11e9-9149-b0e2bdfdcbf0.png)

![places-to-test-3](https://user-images.githubusercontent.com/812192/67326009-fa8fea80-f4e3-11e9-97db-8b3462b27773.png)

**Comment by mcgratay** [comment]
Tested on https://integrations.pressbooks.network/

Resolved
