### ISSUE TITLE
Books not being added to catalog

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-aldine#202]
### Description

A network manager has attempted to add a public book on his network to the site's root catalog, but the book does not appear in the catalog list. No books created on or after August 9, 2019 can be successfully added to the catalog on that particular network. 

### Steps to Reproduce

1. Visit https://ohiostate.pressbooks.pub/wp/wp-admin/network/sites.php?page=pb_network_analytics_booklist as a super admin and find 'Writing Fabulous Features' 
2. Toggle the 'In Catalog' checkmark off and on -- make sure the checkmark is green and the book is set to be included in the catalog. Confirm by looking at https://ohiostate.pressbooks.pub/wp/wp-admin/network/sites.php?orderby=lastupdated&order=desc and the `Pressbooks Publisher in Catalog` value at https://ohiostate.pressbooks.pub/wp/wp-admin/network/site-settings.php?id=209. 
3. Visit the published catalog for Ohio State at https://ohiostate.pressbooks.pub/catalog/page/3/ and look for 'Writing Fabulous Features'. It's not there!

**Expected behavior:** 
The book would be added to the root network's catalog when the 'add to catalog' box is checked for the book.

**Actual behavior:**
The book was not added to the root network's catalog when the 'add to catalog' box was checked.

**More information:**
If you sort the books by creation date and attempt to add various books to the catalog, any book created on August 7, 2019 or before will be successfully added to the catalog (like `SWK 5805: Theories and Biological Basis of Substance Misuse`). However, no books created on August 9, 2019 or after can be added to the catalog (for example: `Insects & Human Affairs: Pests, Plagues, Pollinators and Poisons`). On other networks, this date is different, but the effect is the same. On Wisconsin's network, for example, books created on or before January 31, 2018 (`Teaching Assistantships: Designing for Inclusivity`) can be added, but books created on or after February 1, 2018 (`Materials for Swahili Learners`) cannot. On Michigan's network (which uses Pressbooks Publisher theme instead of Aldine, books created on or before June 16, 2017 can be added, but those created after June 23, 2017 cannot).

**Comment by SteelWagstaff** [comment]
I think this issue may be related to the total number of books on a given network rather than the date itself. Michigan's network has 175+ books, OSU's 180+, and Wisconsin's 420+. Perhaps books registered after a certain number of sites on a given network has been reached can't be added to catalog for some reason?

**Comment by connerbw** [comment]
Looks like `get_sites` defaults to a maximum number of 100.

+ https://github.com/pressbooks/pressbooks-aldine/blob/262df22b4ae8033d3e7f13072331a8273e2f5262/inc/helpers/namespace.php#L61
+ https://developer.wordpress.org/reference/functions/get_sites/

**Comment by connerbw** [comment]
Bug happens when there are more than 100 public books.

**Comment by mcgratay** [comment]
Can't say I tried for 1,000,001 but this issue seems resolved 👍
