### ISSUE TITLE
Catalog filter "Filter by Subject" is not working 

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-aldine#217]
### Description

Issue noted in this [ticket](https://pressbooks.zendesk.com/agent/tickets/2509)

The catalog filter "Filter by Subject" is not working. When selecting any of the subjects to filter by, they do not respond to the click. Can test on two populated catalogs: https://press.rebus.community/catalog/ and https://open.maricopa.edu/catalog/

In addition, we've noticed that the subject field occasionally produces unexpected results in the API. For example, an open source user reports that they've entered 'Musical Instruments' at the primary subject, but the book displays in the catalogue as if the subject had been set as 'Medicine & Nursing'. See https://pressbooks.community/t/strange-subject-mismatch-in-catalog/1557. When I cloned this book to integrations, I saw a series of errors (Sentry error: https://sentry.io/organizations/pressbooks/issues/2135139624/?environment=staging&project=3954026):
![Screenshot from 2021-01-06 07-00-05](https://user-images.githubusercontent.com/13485451/103788347-94fa2200-4ff3-11eb-902e-3b6542e7409f.png)

![Screenshot from 2021-01-06 07-00-27](https://user-images.githubusercontent.com/13485451/103788346-94618b80-4ff3-11eb-92f1-165cc62e3a4f.png)

![Screenshot from 2021-01-06 07-15-41](https://user-images.githubusercontent.com/13485451/103788342-94618b80-4ff3-11eb-9488-08e5c0b845df.png)

![Screenshot from 2021-01-06 07-28-56](https://user-images.githubusercontent.com/13485451/103788341-93c8f500-4ff3-11eb-9e33-70c47599832d.png)

![Screenshot from 2021-01-06 07-29-19](https://user-images.githubusercontent.com/13485451/103788338-93305e80-4ff3-11eb-8973-352ee219d2fa.png)

### Steps to Reproduce

1. Go into any institution's catalog
2. Try to filter by subject under "Filter by Subject"

**Expected behavior:** Catalog should filter when a subject is selected on the "Filter by Subject" options

**Actual behavior:** Nothing changes, no response to the selection

### Notes

Problems may be related to changes we made to the books API to improve performance in Directory: https://github.com/pressbooks/pressbooks/commit/e1d3894da3c5a84e990d55a961574c7ff5625fdc

**Comment by richard015ar** [comment]
PR: https://github.com/pressbooks/pressbooks/pull/2071

Problem was we are showing the Subject name instead the Thema identifier for the primary subject.
When a book is cloned, the identifier saved in the new cloned book for primary subject is a string representing the subject name instead the thema code. So, by default the subject will try to search the thema subject by name instead by code, causing the error displayed.
The change I submitted in the PR will use identifier in the API instead the name, just like before API changes for directory fetcher.

**Comment by SteelWagstaff** [comment]
This fix solves the problem for integrations.
