### ISSUE TITLE
Improve post-login experience for users who do not belong to books

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-aldine#219]
After a user has logged in, we show an 'Admin' link to them if they are a super user or belong to at least one book/blog/site.

https://github.com/pressbooks/pressbooks-aldine/blob/dev/inc/helpers/namespace.php#L183-L202

Proposed change:
We should show the 'admin' link to ALL logged in users. 
If they are a super user or belong to at least one book/blog/site make no change
If they are a user who does not belong to a book/blog/site we the admin link should take them to `wp/wp-admin/user`

```
if ( is_super_admin() || is_user_member_of_blog() ) {
			$items .= sprintf(
				'<li><a href="%1$s">%2$s</a></li>',
				admin_url(),
				__( 'Admin', 'pressbooks-aldine' )
			);
		}
else {
     $items .= sprintf(
				'<li><a href="%1$s/user">%2$s</a></li>',
				admin_url(),
				__( 'Admin', 'pressbooks-aldine' )
			);
```

**Comment by richard015ar** [comment]
Tested on Integrations creating a new normal user from Admin panel, and using SAML user.
On Textopress I created a normal user from admin network panel and it worked as well.

**Comment by SteelWagstaff** [comment]
I can confirm that this works as expected on Integrations and Textopress. All users logging in from the home page will now see an 'Admin' link in their main nav bar. For users without a role in any books, this link takes them to their user admin page.
