### ISSUE TITLE
Page Sections on custom pages do not format correctly

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-aldine#230]
### Description

Typically, when a new page is created at the network level and text is added, it creates a default textbox where text goes into. However, when users add a prebuilt page section (bordered, borderless, accent, etc.) to the page, the page content gets pushed down the page some distance. Example here:
https://open.ocolearnok.org/home/collaborate-with-us/  

### Steps to Reproduce

1. Create a custom page on Pages
2. Add a page section
3. Add text inside the page section

**Expected behavior:** The custom page section should remain where the default content normally appears
![screencapture-open-ocolearnok-org-help-2020-12-16-07_38_52](https://user-images.githubusercontent.com/13485451/102370453-ecb3e900-3f71-11eb-89fa-77cfe389e953.png)

**Actual behavior:** The whole custom page section gets pushed past the header image.
![screencapture-open-ocolearnok-org-home-collaborate-with-us-2020-12-16-07_38_26](https://user-images.githubusercontent.com/13485451/102370450-ec1b5280-3f71-11eb-9a24-df0aefb269b6.png)

**Comment by pb-amy** [comment]
https://pressbooks.zendesk.com/agent/tickets/3245

**Comment by SteelWagstaff** [comment]
The Aldine page section shortcode was apparently only designed to work on the home page template. The workaround is not to use page sections on other types of pages. The CTA shortcodes do work, however. Closing the issue -- this could be addressed when Aldine is next overhauled/replaced: #243
