### ISSUE TITLE
Network language option is available only in English

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-aldine#231]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Aldine](http://github.com/pressbooks/pressbooks-aldine/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using Aldine as your network's root theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-aldine) to see if your bug or enhancement is already listed?

### Description

Issue arose from this client interaction (UQ): https://pressbooks.zendesk.com/agent/tickets/4210

Under Network Admin > Settings > Language, "English (United States)" is the only language available, which makes other languages inaccessible, as well as British/Canadian English with different spellings. In the client issue above, it was referring specifically to the spelling of 'Catalog' which should ideally be 'Catalogue'.

Here's the code in the theme which affects the catalog on Aldine: https://github.com/pressbooks/pressbooks-aldine/blob/2ba9f42520a6aea530e131ffef3c9ea6fabb6e2f/partials/content-front-page.php#L76

### Steps to Reproduce

1. Check that English (US) is the only language available.

**Expected behavior:** More options under languages should be available

**Actual behavior:** Only English (US) is available, and the text throughout Aldine is not changeable as it is hard coded into the theme.

**Comment by SteelWagstaff** [comment]
I just went in and produced English (GB) tranlations for Aldine, McLuhan, and Pressbooks core. These should be available upon next release. We'll need to ask Ho Man to deploy them for affected clients.
