### ISSUE TITLE
Theme Check

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks-aldine#244]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

Some issues are found if you use Theme check on Aldine and McLuhan

### Feature Use Case

Future incompatibilities with other plugins can happen

### Other Notes

https://es.wordpress.org/plugins/theme-check/

# Title: Aldine

Version 1.1.0

Author Pressbooks (Book Oven Inc.)

Author URI https://pressbooks.org

Theme URI https://github.com/pressbooks/pressbooks-aldine/

Description
Aldine is the default theme for the home page of Pressbooks networks. It is named for the Aldine Press, founded by Aldus Manutius in 1494, who is regarded by many as the world’s first publisher.

Running 52623 tests against Aldine using Guidelines Version: 20160523 Plugin revision: 1
One or more errors were found for Aldine.

    REQUIRED: This theme doesn't seem to display tags. Modify it to display tags in appropriate locations.
    REQUIRED: .wp-caption-text css class is needed in your theme css.
    REQUIRED: .gallery-caption css class is needed in your theme css.
    REQUIRED: .bypostauthor css class is needed in your theme css.
    Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
    The domains found are pressbooks-aldine, pressbooks, aldine, Found, found in Trash, list, :, list
    WARNING: Your theme appears to be in the wrong directory for the theme name. The directory name must match the slug of the theme. This theme's correct slug and text-domain is aldine.
    (If this is a child theme, you can ignore this error.)
    WARNING: The theme uses the add_shortcode() function. Custom post-content shortcodes are plugin-territory functionality.
    WARNING: Found a translation function that is missing a text-domain. Function esc_attr_x, with the arguments 'This book is private, so you can’t display it in your catalog.', 'pressbooks-aldine'
    WARNING: Found a translation function that is missing a text-domain. Function esc_attr_x, with the arguments 'Show in Catalog', 'pressbooks-aldine'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'View '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Uploaded to this '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Search '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'New '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Insert into '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Howdy, %s'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Edit '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'All '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Add New '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Add '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' list'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' list navigation'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' Attributes'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' Archives'
    WARNING: file_get_contents was found in the file vendor/pressbooks/mix/inc/Assets.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.

    Line 164: self::$manifest[ $hash ] = json_decode( file_get_contents( $manifest_path ), true );

    Line 193: self::$manifest[ $hash ] = json_decode( file_get_contents( $manifest_path ), true );

    WARNING: .tx .styleci.yml Hidden Files or Folders found.
    REQUIRED: You are not allowed to hide the admin bar.
    REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.
    REQUIRED: Could not find the comment-reply script enqueued. See: Migrating Plugins and Themes to 2.7/Enhanced Comment Display

     <?php if ( is_singular() ) wp_enqueue_script( "comment-reply" ); ?>

    REQUIRED: Could not find add_theme_support( 'automatic-feed-links' ). See: add_theme_support

     <?php add_theme_support( $feature ); ?>

    REQUIRED: vendor/soberwp/intervention/src/Module/AddMenuPage.php. Themes should use add_theme_page() for adding admin pages.

    Line 11: * Uses WordPress function add_menu_page to add an backend page.

    Line 15: * @link https://developer.wordpress.org/reference/functions/add_menu_page/

    Line 72: add_menu_page($this->config->page_title, $this->config->menu_title, $this->

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 72: $labels->filter_items_list = __('Filter ' . strtolower($one) . ' list ');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 71: $labels->uploaded_to_this_item = __('Uploaded to this ' . strtolower($one));

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 70: $labels->insert_into_item = __('Insert into ' . strtolower($one));

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 69: $labels->attributes = __($one . ' Attributes');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 68: $labels->archives = __($one . ' Archives');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 67: $labels->parent_item_colon = __('Parent ' . $one . ':');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 66: $labels->view_item = __('View ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 65: $labels->new_item = __('New ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 64: $labels->edit_item = __('Edit ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 63: $labels->add_new_item = __('Add New ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 62: $labels->add_new = __('Add ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 61: $labels->singular_name = __($one);

    Line 73: $labels->name_admin_bar = __($one);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 47: $labels->items_list = __($many . ' list');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 46: $labels->items_list_navigation = __($many . ' list navigation');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 45: $labels->filter_items_list = __('Filter ' . $many . ' list');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 44: $labels->all_items = __('All ' . $many);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 43: $labels->not_found_in_trash = __('No ' . strtolower($many) . ' found in Trash');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 42: $labels->not_found = __('No ' . strtolower($many) . ' Found');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 41: $labels->search_items = __('Search ' . $many);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 40: $labels->view_items = __('View ' . $many);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 39: $labels->name = __($many);

    Line 48: $labels->menu_name = __($many);

    RECOMMENDED: No reference to the_post_thumbnail() was found in the theme. It is recommended that the theme implement this functionality instead of using custom fields for thumbnails.
    RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
    RECOMMENDED: Tags: is either empty or missing in style.css header.
    INFO: Possible hard-coded links were found in the file inc/activation/namespace.php.

    Line 46: sprintf( '<a href='https://pressbooks.com/about'>%s</a>', __( 'see here', 'pressbooks-aldine' 

    Line 59: sprintf( '<a href='https://pressbooks.com/how-to-make-a-book-with-pressbooks'>%s</a>', __( '4 

    Line 60: sprintf( '<a href='https://guide.pressbooks.com/'>%s</a>', __( 'Guide to Using Pressbooks', 'p

    INFO: Possible hard-coded links were found in the file footer.php.

    Line 63: <a class='footer__pressbooks__icon' href='https://pressbooks.com' title='Pressbooks'>

    Line 70: <p class='footer__pressbooks__links__title'><a href='https://pressbooks.com'><?php printf( __( 'Powered by %s', 'pressbooks-aldi

    Line 74: <li><a href='https://pressbooks.com'><?php _e( 'Open Book Publishing', 'pressbooks-aldin

    Line 72: <li><a href='https://pressbooks.org'><?php _e( 'Open Source', 'pressbooks-aldine' ); ?><

    Line 73: <li><a href='https://pressbooks.education/'><?php _e( 'Open Textbooks', 'pressbooks-aldi

    Line 75: <li><a href='https://pressbooks.education/about'><?php _e( 'Learn More', 'pressbooks-ald

    Line 63: <a class='footer__pressbooks__icon' href='https://pressbooks.com' title='Pressbooks'>

    Line 70: <p class='footer__pressbooks__links__title'><a href='https://pressbooks.com'><?php printf( __( 'Powered by %s', 'pressbooks-aldi

    Line 74: <li><a href='https://pressbooks.com'><?php _e( 'Open Book Publishing', 'pressbooks-aldin

    Line 75: <li><a href='https://pressbooks.education/about'><?php _e( 'Learn More', 'pressbooks-ald

    INFO: partials/content-page-catalog.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 63: include( locate_template( 'partials/book.php' ) );

    INFO: partials/content-front-page.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 58: include( locate_template( 'partials/book.php' ) );

    Line 61: <?php if ( $previous_page || $next_page ) { include( locate_template( 'partials/paged-navigation.php' ) ); } ?>

    INFO: page-catalog.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 36: <?php include( locate_template( 'partials/content-page-catalog.php' ) ); ?>

    INFO: footer.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 24: include( locate_template( 'partials/contact-form.php' ) );

# McLuhan

Version 2.1.0

Author Pressbooks (Book Oven Inc.)

Author URI https://pressbooks.com

Theme URI https://pressbooks.com/themes/pressbooks-book

Description
This theme is named after Canadian media theorist Marshall McLuhan, who coined the phrase “the medium is the message.” It is designed for academic writing and is also suitable for fiction. Headings are set in Cormorant Garamond, and body type is set in Lora.

Running 52745 tests against McLuhan using Guidelines Version: 20160523 Plugin revision: 1
One or more errors were found for McLuhan.

    REQUIRED: This theme doesn't seem to display tags. Modify it to display tags in appropriate locations.
    REQUIRED: Text Domain: is missing from your style.css header.
    REQUIRED: License URI: is missing from your style.css header.
    REQUIRED: .wp-caption-text css class is needed in your theme css.
    REQUIRED: .gallery-caption css class is needed in your theme css.
    REQUIRED: .bypostauthor css class is needed in your theme css.
    RECOMMENDED: This theme contains no sidebars/widget areas. See Widgets API
    Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
    The domains found are pressbooks-book, pressbooks, pressbooks-aldine, presbooks-book, Found, found in Trash, list, :, list
    WARNING: Your theme appears to be in the wrong directory for the theme name. The directory name must match the slug of the theme. This theme's correct slug and text-domain is mcluhan.
    (If this is a child theme, you can ignore this error.)
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'View '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Uploaded to this '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Search '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'New '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Insert into '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Howdy, %s'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Edit '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'All '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Add New '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Add '
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' list'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' list navigation'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' Attributes'
    WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments ' Archives'
    WARNING: file_get_contents was found in the file vendor/pressbooks/mix/inc/Assets.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.

    Line 164: self::$manifest[ $hash ] = json_decode( file_get_contents( $manifest_path ), true );

    Line 193: self::$manifest[ $hash ] = json_decode( file_get_contents( $manifest_path ), true );

    REQUIRED: You are not allowed to hide the admin bar.
    REQUIRED: No content width has been defined. Example:

    if ( ! isset( $content_width ) ) $content_width = 900;

    REQUIRED: Could not find the comment-reply script enqueued. See: Migrating Plugins and Themes to 2.7/Enhanced Comment Display

     <?php if ( is_singular() ) wp_enqueue_script( "comment-reply" ); ?>

    REQUIRED: Could not find add_theme_support( 'automatic-feed-links' ). See: add_theme_support

     <?php add_theme_support( $feature ); ?>

    REQUIRED: vendor/soberwp/intervention/src/Module/AddMenuPage.php. Themes should use add_theme_page() for adding admin pages.

    Line 11: * Uses WordPress function add_menu_page to add an backend page.

    Line 15: * @link https://developer.wordpress.org/reference/functions/add_menu_page/

    Line 72: add_menu_page($this->config->page_title, $this->config->menu_title, $this->

    REQUIRED: get_bloginfo( 'url' ) was found in the file private.php. Use home_url() instead.

    Line 1: <?php $bloginfourl = get_bloginfo( 'url' ); ?>

    Line 10: get_bloginfo( 'url' ) . '/wp-login.php',

    REQUIRED: get_bloginfo( 'url' ) was found in the file page-buy.php. Use home_url() instead.

    Line 20: <p><?php printf( __( 'You can buy <a href='%1$s'>%2$s</a> by following any of the links below:', 'pressbooks-book' ), get_bloginfo( 'url' ), get_bloginfo( 'name' ) ); ?></p>

    REQUIRED: bloginfo( 'url' ) was found in the file private.php. Use echo esc_url( home_url() ) instead.

    Line 1: <?php $bloginfourl = get_bloginfo( 'url' ); ?>

    Line 10: get_bloginfo( 'url' ) . '/wp-login.php',

    REQUIRED: bloginfo( 'url' ) was found in the file page-buy.php. Use echo esc_url( home_url() ) instead.

    Line 20: <p><?php printf( __( 'You can buy <a href='%1$s'>%2$s</a> by following any of the links below:', 'pressbooks-book' ), get_bloginfo( 'url' ), get_bloginfo( 'name' ) ); ?></p>

    REQUIRED: bloginfo( 'template_directory' ) was found in the file page-buy.php. Use echo esc_url( get_template_directory_uri() ) instead.

    Line 24: <li class='buy-amazon'><a href='<?php print $urls['amazon']; ?>' class='bookstore-logo-link logo'><img src='<?php bloginfo( 'template_directory' ); ?>/dist/images/amazon.png' width='100' he

    Line 28: <li class='buy-oreilly'><a href='<?php print $urls['oreilly']; ?>' class='bookstore-logo-link logo'><img src='<?php bloginfo( 'template_directory' ); ?>/dist/images/oreilly.png' width='100' h

    Line 32: <li class='buy-barnes-and-noble'><a href='<?php print $urls['barnesandnoble']; ?>' class='bookstore-logo-link logo'><img src='<?php bloginfo( 'template_directory' ); ?>/dist/images/barnes-and-noble.png' widt

    Line 36: <li class='buy-kobo'><a href='<?php print $urls['kobo']; ?>' class='bookstore-logo-link logo'><img src='<?php bloginfo( 'template_directory' ); ?>/dist/images/kobo.png' width='54' heigh

    Line 40: <li class='buy-ibooks'><a href='<?php print $urls['ibooks']; ?>' class='bookstore-logo-link logo'><img src='<?php bloginfo( 'template_directory' ); ?>/dist/images/ibooks.png' width='34' hei

    REQUIRED: bloginfo( 'stylesheet_directory' ) was found in the file header.php. Use echo esc_url( get_stylesheet_directory_uri() ) instead.

    Line 7: <link rel='shortcut icon' href='<?php bloginfo( 'stylesheet_directory' ); ?>/favicon.ico' /><?php // TODO ?>

    RECOMMENDED: Screenshot size should be 1200x900, to account for HiDPI displays. Any 4:3 image size is acceptable, but 1200x900 is preferred.
    RECOMMENDED: Screenshot dimensions are wrong! Ratio of width to height should be 4:3.
    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 72: $labels->filter_items_list = __('Filter ' . strtolower($one) . ' list ');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 71: $labels->uploaded_to_this_item = __('Uploaded to this ' . strtolower($one));

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 70: $labels->insert_into_item = __('Insert into ' . strtolower($one));

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 69: $labels->attributes = __($one . ' Attributes');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 68: $labels->archives = __($one . ' Archives');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 67: $labels->parent_item_colon = __('Parent ' . $one . ':');

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 66: $labels->view_item = __('View ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 65: $labels->new_item = __('New ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 64: $labels->edit_item = __('Edit ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 63: $labels->add_new_item = __('Add New ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 62: $labels->add_new = __('Add ' . $one);

    RECOMMENDED: Possible variable $one found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 61: $labels->singular_name = __($one);

    Line 73: $labels->name_admin_bar = __($one);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 47: $labels->items_list = __($many . ' list');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 46: $labels->items_list_navigation = __($many . ' list navigation');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 45: $labels->filter_items_list = __('Filter ' . $many . ' list');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 44: $labels->all_items = __('All ' . $many);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 43: $labels->not_found_in_trash = __('No ' . strtolower($many) . ' found in Trash');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 42: $labels->not_found = __('No ' . strtolower($many) . ' Found');

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 41: $labels->search_items = __('Search ' . $many);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 40: $labels->view_items = __('View ' . $many);

    RECOMMENDED: Possible variable $many found in translation function in vendor/soberwp/intervention/src/Labels.php. Translation function calls must NOT contain PHP variables.

    Line 39: $labels->name = __($many);

    Line 48: $labels->menu_name = __($many);

    RECOMMENDED: No reference to post-thumbnails was found in the theme. If the theme has a thumbnail like functionality, it should be implemented with add_theme_support( "post-thumbnails" )in the functions.php file.
    RECOMMENDED: No reference to nav_menu's was found in the theme. Note that if your theme has a menu bar, it is required to use the WordPress nav_menu functionality for it.
    RECOMMENDED: No reference to the_post_thumbnail() was found in the theme. It is recommended that the theme implement this functionality instead of using custom fields for thumbnails.
    RECOMMENDED: No reference to add_theme_support( "custom-header", $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
    RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
    RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.
    RECOMMENDED: Could not find the file readme.txt in the theme. Please see Theme_Documentation for more information.
    RECOMMENDED: Tags: is either empty or missing in style.css header.
    INFO: Possible hard-coded links were found in the file footer.php.

    Line 18: <a class='footer__pressbooks__icon' href='https://pressbooks.com' title='Pressbooks'>

    Line 25: <p class='footer__pressbooks__links__title'><a href='https://pressbooks.com'><?php printf( __( 'Powered by %s', 'pressbooks-book

    Line 29: <li><a href='https://pressbooks.com'><?php _e( 'Open Book Publishing', 'pressbooks-book'

    Line 30: <li><a href='https://pressbooks.com/about'><?php _e( 'Learn More', 'pressbooks-book' ); 

    Line 27: <li><a href='https://pressbooks.org'><?php _e( 'Open Source', 'pressbooks-book' ); ?></a

    Line 28: <li><a href='https://pressbooks.education/'><?php _e( 'Open Textbooks', 'pressbooks-book

    Line 18: <a class='footer__pressbooks__icon' href='https://pressbooks.com' title='Pressbooks'>

    Line 25: <p class='footer__pressbooks__links__title'><a href='https://pressbooks.com'><?php printf( __( 'Powered by %s', 'pressbooks-book

    Line 29: <li><a href='https://pressbooks.com'><?php _e( 'Open Book Publishing', 'pressbooks-book'

    Line 30: <li><a href='https://pressbooks.com/about'><?php _e( 'Learn More', 'pressbooks-book' ); 

    Line 30: <li><a href='https://pressbooks.com/about'><?php _e( 'Learn More', 'pressbooks-book' ); 

    INFO: single.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 18: include( locate_template( 'partials/content-single.php' ) );

    Line 20: include( locate_template( 'partials/content-single-legacy.php' ) );

    INFO: partials/content-cover-toc.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 3: <?php include( locate_template( 'partials/content-toc.php' ) ); ?>

    INFO: page-cover.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 14: include( locate_template( 'partials/content-cover-book-header.php' ) );

    Line 15: include( locate_template( 'partials/content-cover-toc.php' ) );

    Line 16: include( locate_template( 'partials/content-cover-book-info.php' ) );

    Line 17: include( locate_template( 'partials/content-cover-metadata.php' ) );

    INFO: index.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 12: <?php include( locate_template( 'partials/content-toc.php' ) ); ?>

    INFO: header.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

    Line 105: <?php include( locate_template( 'partials/content-toc.php' ) ); ?>

**Comment by SteelWagstaff** [comment]
We don't list our themes in wordpress.org so this isn't relevant for us. Closing.
