### ISSUE TITLE
Catalog page - Aldine requires a more fine tune

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks-aldine#245]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [X] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To be able to search with more fine tune.

### Feature Use Case

What if we have all the books or the most of the books from just one subject.?
What if we have books in different languages?
What if we have translations?

If the network belongs to one department or to one specialiced publishing house, like second languages publishing company or commics or ...  all the books are form the same subject, so the filters do not help.

**Comment by SteelWagstaff** [comment]
Closing in favor of #242, #342, #343
