### ISSUE TITLE
Creating a CAPTCHA for the contact submission form on Aldine

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-aldine#253]
### Feature Description

Request from this client ticket: https://pressbooks.zendesk.com/agent/tickets/5032 

On the Aldine theme, there is a [contact submission form](https://networkmanagerguide.pressbooks.com/chapter/customizing-network/#contactform) that can be included.

Currently, anyone can send an email through the submission form, with no blockers on who is able to send the inquiry. This can lead to random, irrelevant emails, especially when the submission form is found through search engines or other places in the web (i.e. questions like "Can you please include our resource on your book?" etc.)

### Feature Use Case

This will better streamline the kind of emails that network managers get through the submission form, and create an extra blocker to make sure that whoever is sending the inquiry is a valid and real user, as opposed to a bot.

**Comment by SteelWagstaff** [comment]
@pb-amy we have this (honeypot technique) protecting this form: https://github.com/pressbooks/pressbooks-aldine/issues/134. Is it no longer working?

**Comment by SteelWagstaff** [comment]
Honeypot technique is still present and operational. Closing issue.
