### ISSUE TITLE
Replace Lorem Ispum with Desired Text blocks for new hosted networks

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-aldine#272]
When a new network is deployed, Aldine has generic Lorem Ipsum for the home page content blocks: 
![Screenshot from 2021-07-26 08-19-25](https://user-images.githubusercontent.com/13485451/127014640-40a7897c-09fd-4adc-9632-64a1f6d1f531.png)

Replace this with desired text for new networks. Need copy from Leigh and Amy.

See https://github.com/pressbooks/sample-infrastructure/blob/master/trellis/deploy-hooks/aldine_page_on_front.txt

**Comment by richard015ar** [comment]
See: https://github.com/pressbooks/sample-infrastructure/blob/9100a1aa744a5aa3370b553861670bb9b4bfca3a/trellis/deploy-hooks/aldine_page_on_front.txt
Could be likely the place to change

**Comment by LeighKP** [comment]
Copy for default block:

Looking for open textbooks to adopt? Visit Pressbooks Directory and browse over 2500 resources. You can clone books directly to your Pressbooks network where you can edit, adapt, and enhance with interactive activities. 
_Add hyperlink to “clone books” in the third sentence: https://guide.pressbooks.com/chapter/book-cloning/ 
CTA Button:_ Visit Pressbooks Directory

**Comment by pb-amy** [comment]
Wondering to get started with your Pressbooks project? Register for a [PressbooksEDU webinar](https://networkmanagerguide.pressbooks.com/chapter/end-user-training/)! It will cover everything from creating your book, to importing content, uploading media, applying a theme and exporting your book.  
CTA: [Register for a Webinar](https://pressbooks.com/webinar)

**Comment by pb-amy** [comment]
Need help on your Pressbooks project? Please refer to our [User Guide](https://guide.pressbooks.com/) to read our documentation, our [Youtube channel](https://youtube.com/pressbooks) to watch short video tutorials, or please contact (_maybe link_ **#contact**) your Network Manager for direct assistance.
CTA: [Pressbooks Support Page](https://pressbooks.com/support)

**Comment by SteelWagstaff** [comment]
Sample text (with small modifications) has been added to integrations for review: https://integrations.pressbooks.network/#contact. If this looks good to Amy & Leigh, happy to add this to our new hosted networks as the default.
![screencapture-integrations-pressbooks-network-2021-08-10-16_08_24.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/f3cfe558-bd44-4d07-85ad-191dfdcfca11)

**Comment by LeighKP** [comment]
I have some copy edits:

For the Get Help box: It says "use the contact form _below_" but right below the paragraph you have a link to the support page. I recommend using "this contact form" instead and linking that text to the form.
I would also recommend changing the Get Help header to read "Need Help?" This would make it so we don't have two headers that start with "Get."

For the Get Started box: I would remove the final exclamation point. 

Styling request:
Can the button on the Directory box be in line with the button on the Get Started box?

**Comment by pb-amy** [comment]
I agree with everything Leigh has said above. I also think the support and webinar boxes can be switched if need be.

**Comment by SteelWagstaff** [comment]
Tested and looking good on https://qatesttemp.pressbooks.network/
