### ISSUE TITLE
'Help' page on new networks contain the wrong link

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-aldine#298]
### Description

New networks are deployed with a default page at a URL that ends in `/help` -- example: https://sheffield.pressbooks.pub/help/

<img width="768" alt="Screen Shot 2021-12-07 at 5 08 44 PM" src="https://user-images.githubusercontent.com/61845107/145113660-79a7326d-a918-445c-af30-5832326b8fbc.png">

These pages contain the wrong link for "4 Step Guide to Making a Book on Pressbooks." It points to a broken page. It _should_ point to here: https://guide.pressbooks.com/front-matter/the-simple-5-step-guide-to-making-a-book-with-pressbooks/, and the text should be corrected to match text provided here: https://docs.google.com/document/d/1ely2AYkfh3yDTU7KeB03A9rIJQSbjTbLOj_kOB7Skqk/edit

### Steps to Reproduce

1. Go to a network and head to their help page: [Network-URL]/help/
2. Click on "4 Step Guide to Making a Book on Pressbooks"

**Expected behavior:** It should point to a valid link

**Actual behavior:** Link is broken

## Notes
This page is created upon theme/network activation using this function: https://github.com/pressbooks/pressbooks-aldine/blob/0ad64a509807906dac4f59572d3ec6212735ee2f/inc/activation/namespace.php#L53-L66

**Comment by SteelWagstaff** [comment]
Tested and working as expected on integrations. Awaiting final copy check from Amy.
