### ISSUE TITLE
Database Error with Aldine 1.13 catalog page "get_institutions"

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-aldine#315]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Aldine](http://github.com/pressbooks/pressbooks-aldine/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using Aldine as your network's root theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-aldine) to see if your bug or enhancement is already listed?

### Description

We are getting a fatal error that is crashing our /catalog page.

We are running the latest version of Pressbooks and Aldine. When I go to the logs, the thing that jumps out at me is that the error includes references to “get_institutions” which is a new feature in Pressbooks.

Our website is pressbooks.sunycreate.cloud, every other page is working as expected, except for pressbooks.sunycreate.cloud/catalog which shows a database error.

From my logs:
[08-Feb-2022 18:17:48 UTC] PHP Fatal error: Uncaught Error: Call to undefined function Pressbooks\Metadata\get_institutions() in /home/sunycreate/pressbooks.sunycreate.cloud/wp-content/themes/pressbooks-aldine/inc/helpers/namespace.php:161
Stack trace:
#0 /home/sunycreate/pressbooks.sunycreate.cloud/wp-content/themes/pressbooks-aldine/page-catalog.php(29): Aldine\Helpers\get_institutions()
#1 /home/sunycreate/pressbooks.sunycreate.cloud/wp-includes/template-loader.php(106): include(’/home/sunycreat…’)
#2 /home/sunycreate/pressbooks.sunycreate.cloud/wp-blog-header.php(19): require_once(’/home/sunycreat…’)
#3 /home/sunycreate/pressbooks.sunycreate.cloud/index.php(17): require(’/home/sunycreat…’)
#4 {main}
thrown in /home/sunycreate/pressbooks.sunycreate.cloud/wp-content/themes/pressbooks-aldine/inc/helpers/namespace.php on line 161

### Steps to Reproduce

I don't have definitive steps to reproduce on other sites, but you can reproduce by visiting pressbooks.sunycreate.cloud/catalog
<img width="1363" alt="Screen Shot 2022-02-08 at 2 04 57 PM" src="https://user-images.githubusercontent.com/29982981/153057669-28564435-e789-4f60-b085-0039a246ea98.png">

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: https://pressbooks.sunycreate.cloud/

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 98.0.4758.80
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36

#### WordPress Configuration

Network URL: https://pressbooks.sunycreate.cloud/
Network Type: Subdomain
Version: 5.8.3
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.31.1
Root Theme: Aldine
Root Theme Version: 1.13.0

#### Pressbooks Dependencies

Epubcheck: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Git Updater: 10.6.13
Limit Login Attempts Reloaded: 2.23.2
Pressbooks: 5.31.1
Pressbooks Stats: 1.6.3

#### Root Blog Active Plugins

Git Updater: 10.6.13
Limit Login Attempts Reloaded: 2.23.2
Pressbooks: 5.31.1
Pressbooks Stats: 1.6.3

#### Inactive Plugins

Candela Citation: 0.2.3
H5P: 1.15.4
Hypothesis: 0.6.0
Pressbooks Shortcode Handler: 0.1
Pressbooks Stats: 1.6.4
TablePress: 1.14
WordPress Importer: 0.7
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.3.20
MySQL Version: 5.7.30
Webserver Info: Apache

#### PHP Configuration

Memory Limit: 1024M
Upload Max Size: 128M
Post Max Size: 256M
Upload Max Filesize: 128M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: N/A
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.71.0
imagick: Not Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
Thanks for reporting @beckej13820 -- at first glance, I notice you're running Pressbooks 5.31.1. I think we probably should have made this more explicit in Aldine, but the latest Aldine release and latest releases of Pressbooks/Pressbooks-book are all linked. My first recommendation would be either going back to Aldine 1.12 or bumping Pressbooks to 5.32 and Pressbooks-book/McLuhan 2.16. Either way, this is in our queue for tomorrow's bug scrub.
