### ISSUE TITLE
Add support for new pressbooks network catalog

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-aldine#345]
As a developer I would like to display a new catalog page through the new plugin pressbooks-network-catalog that replaces the current catalog page. 

DoD: Allow to replace the current aldine catalog page with a different one from pressbooks-network-catalog plugin.

Note: adding a new hook could be a simple and good solution.

**Comment by SteelWagstaff** [comment]
Could what we want to accomplish be done with a WordPress page template? https://developer.wordpress.org/themes/template-files-section/page-template-files/

**Comment by richard015ar** [comment]
It is done in `pbald-345-catalogSupport`. More changes will be added before a PR is created.
