### ISSUE TITLE
Deleting Front Page Unrecoverable

### ISSUE THREAD

**Issue by alexdryden** [pressbooks/pressbooks-aldine#402]
### Description

Deleting the page designated as the Network Home Page prevents user from selecting an alternate page as the Network Home Page

### Steps to Reproduce

1. Go to *Pressbooks Network Name* => Dashboard => Pages => All Pages
2. For the page that is designated "Front Page", select trash
3. Go to Appearance > Customize > Front Page Setting

**Expected behavior:** 
There should be a select input with available pages that the user can set as the Front Page

**Actual behavior:** 
The "Network Home Page" select field is not displayed  

### Screenshots

Before Deleting the Network Home Page page
<img width="1466" alt="Screenshot 2023-03-08 at 3 08 12 PM" src="https://user-images.githubusercontent.com/47127862/223837500-8dee294c-23bd-45bd-85b8-7af33d312bc9.png">

Delete the front page
<img width="1466" alt="Pages" src="https://user-images.githubusercontent.com/47127862/223838836-960d3bd3-d19e-47bb-8438-9e90c3e8510f.png">

Nothing is set as the front page
<img width="1470" alt="deleted" src="https://user-images.githubusercontent.com/47127862/223840271-62f360c2-fb17-4250-bc3c-caf9167d3ab4.png">

Select does not display
<img width="1470" alt="Screenshot 2023-03-08 at 3 09 06 PM" src="https://user-images.githubusercontent.com/47127862/223837478-e7d3ae8f-bba1-465f-b4bb-219796ac370d.png">

**Comment by SteelWagstaff** [comment]
Tested and works as expected. Ready for release.
