### ISSUE TITLE
Site Title and Tagline pushed above viewfinder in mobile view

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-aldine#404]
### Description

If I navigate to a network home page in mobile view, the entry-header (with Site Title and Tagline) is pushed above the viewable area of the screen. 

```
<header class="entry-header">
<h1 class="entry-title">Network Name</h1>
<p class="entry-description">Network Tagline</p>
</header>
```

It's there, but not visible. 

<img width="642" alt="Screenshot 2023-03-22 at 9 00 13 AM" src="https://user-images.githubusercontent.com/44182629/226965110-2a278d94-fe00-41b4-a9ff-29a2c05cea62.png">

### Steps to Reproduce

1. Navigate to a network home page in mobile view.

**Expected behavior:** The Site Title and Tagline are visible.

**Actual behavior:** The Site Title and Tagline are pushed above the viewable area of the screen.

**Comment by SteelWagstaff** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-aldine/404?planning-poker) with Zenhub @arzola @fdalcin

**Comment by SteelWagstaff** [comment]
Tested and works as expected.
