### ISSUE TITLE
Default content

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-aldine#6]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Aldine](http://github.com/pressbooks/pressbooks-aldine/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using Aldine as your network's root theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-aldine) to see if your bug or enhancement is already listed?

### Description

We need one paragraph of content for each of the following pages, which will be created upon activation:

- [x] About (brief "about Pressbooks" copy, with link to learn more [here](https://pressbooks.com/about/) or elsewhere)
- [x] Help (brief "how to use Pressbooks" copy, with link to [here](https://pressbooks.com/how-to-make-a-book-with-pressbooks/) or elsewhere)

### Steps to Reproduce

Not applicable.

### System Information

Aldine: 1.0.0-dev

**Comment by pressbooksapurva** [comment]
### About

Pressbooks is simple book production software. You can use Pressbooks to publish textbooks, scholarly monographs, syllabi, white papers, and more in multiple formats including:

- MOBI (for Kindle ebooks)
- EPUB (for all other ebookstores)
- designed PDF (for print-on-demand and digital distribution)

Pressbooks is used by authors, publishers and educational institutions around the world. 

For more information about Pressbooks, [see here](https://pressbooks.com/about/) or [contact us](mailto:sales@pressbooks.com).

### Help 

The easiest way to get started with Pressbooks is to follow our [4 Step Guide to Making a Book on Pressbooks](https://pressbooks.com/how-to-make-a-book-with-pressbooks/). As well, you can review our comprehensive [Guide for Educational Publishing](https://eduguide.pressbooks.com/).

You may find some of your questions answered in our FAQ section below.

If you require further assistance, contact your network manager or [Pressbooks Support](mailto:support@pressbooks.com).

**Comment by PressbooksLiz** [comment]
Tiny edits coming to the above, Ned. Hold off for 10 min.

**Comment by greatislander** [comment]
I'm holding off until after lunch 🌮

**Comment by PressbooksLiz** [comment]
All clear--we're breaking for lunch. Have at!

**Comment by pressbooksapurva** [comment]
### About

Pressbooks is simple book production software. You can use Pressbooks to publish fiction and non-fiction books, textbooks, scholarly monographs, syllabi, white papers, and more in multiple formats including:

- MOBI (for Kindle ebooks)
- EPUB (for all other ebookstores)
- designed PDF (for print-on-demand and digital distribution)

Pressbooks is used by educational institutions around the world as well as authors and publishers. 

For more information about Pressbooks, [see here](https://pressbooks.com/about).

### Help 

The easiest way to get started with Pressbooks is to follow our [5 Step Guide to Making a Book on Pressbooks](https://pressbooks.com/how-to-make-a-book-with-pressbooks). Or, you can review our [Guide to Using Pressbooks](https://guide.pressbooks.com/).

If you require further assistance, please contact your network manager.

**Comment by PressbooksLiz** [comment]
Ned, hold off, more discussion.

**Comment by zwhpressbooks** [comment]
Ok @greatislander, one last edit was made to Apurva's last comment and we can move forward. Thanks for your patience :)
